### ISSUE TITLE
Edits to testing tutorial

### ISSUE THREAD

**Issue by kshia** [YaleSTC/android_testing_training#5]
The first example for the `getCacheSize` method is already static, so after the first example it should say that we tested a static public method.

In the second example, the method needs to be changed to private AND non-static. However, this causes an error in the VolleyRequestQueue.java file, so the lines 26-28 (`imgLoader = new ImageLoader(reqQueue, new LruBitmapCache(LruBitmapCache.getCacheSize(context)));`) need to be commented out in order for the code to compile. Since its no longer static, you must instantiate a LruBitmapCache object.

This is a good link for how to write a test for a private method since `getMethod()` will not work for private methods. http://stackoverflow.com/questions/34571/how-do-i-test-a-class-that-has-private-methods-fields-or-inner-classes

**Comment by stswidwinski** [comment]
Fixed! :-)
